server:
  hostname: localhost
  port: ${PORT:8880}
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings